-- AlterTable
ALTER TABLE "Subject" ADD COLUMN     "assessmentMax" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "examMax" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "projectMax" INTEGER NOT NULL DEFAULT 30;
